---
api:
  url: https://fhir-ehr.sandboxcerner.com/dstu2/0b8a0111-e8e6-4c26-a91c-5069cbc6b1ca/
  patient: 1316024

auth:
  strategy: authorization_code
  client_id: 0e00e6a7-dc4c-45a5-b36c-974cb8f9cb5e
  client_secret:
  scope: launch patient/Patient.read patient/Encounter.read patient/Observation.read patient/Condition.read patient/MedicationOrder.read patient/MedicationStatement.read patient/MedicationDispense.read patient/MedicationAdministration.read patient/AllergyIntolerance.read patient/Procedure.read patient/Immunization.read patient/DocumentReference.read online_access
  sign_in_steps:
    - element: "#j_username"
      send_keys: "portal"
    - element: "#j_password"
      send_keys: "portal"
  authorize_steps:
    - element: "#loginButton"
      click: True
  cancel_steps:
    - element: "#cancelButton"
      click: True
  extra_launch_params:
    launch: df66fbf6-1056-4b42-9ac9-a47765e74afd
